targets:
    $default:
        builders:
            drift_dev:
                enabled: true
            isar_community_generator:
                enabled: true
            riverpod_generator:
                enabled: true
