name: sony_jaya
description: SONY JAYA - IPOS 5 Auto-Control HPP
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"      # <- naik, karena source_gen 2.0.0 butuh Dart 3.6
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  # Otak multifungsi
  drift: ^2.26.1             # <- naik biar sama-sama source_gen 2.x
  sqlite3_flutter_libs: ^0.5.42
  drift_flutter: ^0.2.7
  
  # Saraf super Reaktif
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  
  # Otot Background
  # workmanager: ^0.5.2 ganti untuk fluttter 3.29
    workmanager:
      git:
        url: https://github.com/MaxRoversTech/flutter_workmanager.git
        ref: fix/android-embedding-v2
  
  # Cache Cepat
  isar_community: ^3.3.0-dev.1
  isar_community_flutter_libs: ^3.3.0-dev.1

  # Utils Toko Bangunan
  path_provider: ^2.1.2
  path: ^1.9.0     # <- turun, karena flutter_test 3.29 ngunci 1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.26.1
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5
  isar_community_generator: ^3.3.0-dev.1
  flutter_lints: ^3.0.2
