name: sony_jaya
description: SONY JAYA - IPOS 5 Auto-Control HPP
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"   
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  # Otak multifungsi
  drift: ^2.28.2
  sqlite3_flutter_libs: ^0.5.42
  drift_flutter: ^0.2.7

  # Saraf super Reaktif - NAIK KE 3.x biar source_gen 4.x
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0

  # Otot Background - fix buat 3.47.5
  workmanager: ^0.10.10 #ganti untuk flutter 3.47.5

  # Cache Cepat
  isar_community: ^3.3.2
  isar_community_flutter_libs: ^3.3.2

  # Utils Toko Bangunan dan backup dan share wa
  path_provider: ^2.1.2
  path: ^1.9.0
  file_picker: ^8.1.2
  share_plus: ^10.1.2
  http: ^1.2.0
  screenshot: ^2.3.0
  printing: ^5.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.28.2
  build_runner: ^2.8.0 # FIX dari 2.7.0 - support analyzer 8
  riverpod_generator: ^3.0.0 # <- NAIK dari 2.6.5 ke 3.0.0 biar source_gen ^4.0.0
  isar_community_generator: ^3.3.2
  flutter_lints: ^4.0.0
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.0

dependency_overrides:
  # FIX Dart 3.14 dev bawa analyzer 13, riverpod_generator 3.0 butuh analyzer 7-9
  # paksa naik biar gak bentrok sama flutter_test 0.12.20
  analyzer: ^8.1.0
  matcher: 0.12.20
  test_api: 0.7.14