import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../core/database/local_database.dart';
import '../../inventory/providers/inventory_provider.dart';
enum TipeHarga { ecer, agen }
class CartItem { final BarangData barang; int qty; double hargaJual; TipeHarga tipe; CartItem({required this.barang, this.qty=1, required this.hargaJual, required this.tipe}); double get subtotal => qty*hargaJual; double get laba => (hargaJual-barang.hppAverage)*qty; double get marginPersen => barang.hppAverage==0?0: ((hargaJual-barang.hppAverage)/barang.hppAverage*100); }
class CartNotifier extends Notifier<List<CartItem>> { @override List<CartItem> build() => []; void tambahItem(BarangData barang, {int qty=1, required TipeHarga tipeHarga}) { final harga = tipeHarga==TipeHarga.ecer? barang.hargaEcer : barang.hargaAgen; if(harga<barang.hppAverage) throw Exception('MARGIN GUARD: Harga di bawah HPP Rp ${barang.hppAverage.toStringAsFixed(0)}!'); if(qty>barang.stok) throw Exception('Stok tidak cukup! Sisa ${barang.stok}'); final idx = state.indexWhere((e)=>e.barang.id==barang.id && e.tipe==tipeHarga); if(idx>=0){ final exist=state[idx]; final newQty=exist.qty+qty; if(newQty>barang.stok) throw Exception('Stok tidak cukup!'); state=[for(int i=0;i<state.length;i++) if(i==idx) CartItem(barang: barang, qty: newQty, hargaJual: harga, tipe: tipeHarga) else state[i]]; } else { state=[...state, CartItem(barang: barang, qty: qty, hargaJual: harga, tipe: tipeHarga)]; } } void updateQty(int barangId, TipeHarga tipe, int newQty){ if(newQty<=0){ hapusItem(barangId, tipe); return; } state=state.map((e)=> e.barang.id==barangId && e.tipe==tipe? CartItem(barang: e.barang, qty: newQty, hargaJual: e.hargaJual, tipe: e.tipe): e).toList(); } void hapusItem(int barangId, TipeHarga tipe) => state=state.where((e)=>!(e.barang.id==barangId && e.tipe==tipe)).toList(); void clearCart()=>state=[]; Future<void> checkout() async { if(state.isEmpty) return; final db=ref.read(localDbProvider); final inv=ref.read(inventoryControllerProvider); for(var c in state){ await db.transaksiDao.prosesPenjualan(barangId: c.barang.id, qtyInput: c.qty, hargaJualPerSatuanInput: c.hargaJual, tipe: c.tipe==TipeHarga.ecer?'eceran_kasir':'agen_kasir'); await inv.refreshCacheAfterCheckout(c.barang.id); } clearCart(); } }
final cartProvider = NotifierProvider<CartNotifier, List<CartItem>>(CartNotifier.new);
enum FilterKategoriHarga { semua, ecer, agen, marginTinggi }
class KasirFilter { String search=''; FilterKategoriHarga kategori=FilterKategoriHarga.semua; }
class KasirFilterNotifier extends Notifier<KasirFilter> { @override KasirFilter build()=>KasirFilter(); void setSearch(String v)=> state=KasirFilter()..search=v..kategori=state.kategori; void setKategori(FilterKategoriHarga k)=> state=KasirFilter()..search=state.search..kategori=k; }
final kasirFilterProvider = NotifierProvider<KasirFilterNotifier, KasirFilter>(KasirFilterNotifier.new);
