# .github/workflows/flutter.yml
name: Build APK Debug
on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle 8.10.2 - tanpa curl, tanpa 9 byte
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.10.2

      - name: Setup Flutter Stable 3.24.5
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: 'stable'
          cache: true

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y sqlite3 libsqlite3-dev clang cmake ninja-build pkg-config

      - name: Fix pubspec biar cocok sama stable
        run: |
          sed -i 's/>=3.47.0/>=3.24.0/g' pubspec.yaml
          sed -i 's/>=3.47.5/>=3.24.0/g' pubspec.yaml
          sed -i 's/>=3.10.0/>=3.5.0/g' pubspec.yaml
          sed -i 's/flutter_riverpod: \^3.0.0/flutter_riverpod: ^2.6.1/' pubspec.yaml
          cat pubspec.yaml | grep -A3 environment

      - name: Build APK Debug
        run: |
          flutter clean
          flutter pub get
          flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk